### ISSUE TITLE
Provide list of taxa not included in the synthetic tree

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/propinquity#10]
We want to be able to provide the warning messages referenced in [this issue](https://github.com/OpenTreeOfLife/opentree/issues/310#issuecomment-187322741) when a user searches for a taxon that is in the taxonomy but not the synthetic tree.

**Comment by mtholder** [comment]
I'm working on this now. It is part of a new `unprune-and-name` tool in otcetera (there may still be bugs in the unprune part).  It seems best to attach the information about these "lost" taxa in the `annotations.json` file that propinquity produces (but I'm open to putting them in a separate JSON file, if anyone feels strongly about that).  In the current version of otcetera, we produce a file that looks like this:

```
{
    "non_monophyletic_taxa": {
        "ott4": {
            "attachment_points": {
                "mrcaott1ott2": [
                    "ott2"
                ],
                "mrcaott1ott9": [
                    "ott1"
                ]
            },
            "mrca": "mrcaott1ott2"
        }
    }
}
```

This would be interpreted as:
  1. the only OTT ID that is not monophyletic in the synthetic tree is ott4 (we can conclude this because "ott4" is the only property in `non_monophyletic_taxa`)
  2.  "mrcaott1ott2" is the name of the node in the synthetic tree that is the MRCA of all of the members of "ott4"
  3. There are 2 nodes in the synthetic tree ("mrcaott1ott2" and "mrcaott1ott9") which are parents to subtrees which consist entirely of members of ott4. These are the nodes where members of ott4 attach to the rest of the tree. 
  4. If you are looking at "mrcaott1ott2" it will have some children that contain taxa that are not part of ott4, but it will have one child named "ott2" that consists entirely of taxa from the taxon ott4

This format would be very easy to tweak at this point, so everyone should definitely chime in with requests/objections.

It seems like we are not going to put this in the v3 API, but it may be the basis for information that is returned when `subtree` or `node_info` return a 400 status code in cases where a valid OTT ID is passed in as an argument, but that taxon is not found in the tree.

**Comment by jimallman** [comment]
> it may be the basis for information that is returned when subtree or node_info return a 400 status code

Sure, this JSON could form the body of a 400 response.

**Comment by kcranston** [comment]
This seems good to me. Allows us to provide annotations:
* when someone searches for ott4
* at mrcaott1ott2, about why all of these children-of-ott4 are here
* reciprocal annotations at ott1 and ott2 about 'look here for the rest of ott4'

Where would we get the info about what sources conflict with ott4?

**Comment by mtholder** [comment]
"Where would we get the info about what sources conflict with ott4?" that is tricky. ott4 might be non-monophyletic because of an interaction between other nodes. So there may not be any source node that conflicts with it. In general the source nodes that are in `supported_by` (or are `partial_path_of`) for the attachment points ("mrcaott1ott2" and "mrcaott1ott9" in this example) are the candidates for nodes that are causing the non-monophyly of ott4.

I think that taken together those groupings are sufficient for non-monophyly of ott4, but (without further analysis) one could not conclude that any one of them is necessary for non-monophyly of ott4.

**Comment by bredelings** [comment]
Any thoughts on handling the case where a group A happens to have a single non-A taxon deeply nested within the group?

(((((A1,B),A2),A3),A4),A5)mrca-A;

In this case, we'd list the attachment points as A1, A2, A3, A4, A5, etc.  The user might with to know which non-A taxa are present in the clade.

There might be a number of queries to keep in mind:
- which non-A taxa are under this node?
- where are the A taxa under this node?
- which groups under this node contain no non-A taxa?
- of the N children of this node, perhaps only n contain taxa in A -- which ones?
- of the N chidlren of this node, perhaps only n contain taxa not in A - which ones?

Karen - thoughts?  This seems to relate to our white-board discussion.

**Comment by kcranston** [comment]
Maybe I misunderstood the definition of attachment point. In @mtholder
description, the attachment points are parents of subtrees that only
contain members of the non-monophyletic taxon. In your case, only the
single tip A1 fits that description.

I agree that having a list of the intervening non-A tips is another good
piece of information when trying to answer the question "why is A not
present in the tree".

On Mon, Mar 14, 2016 at 3:08 PM, Benjamin Redelings <
notifications@github.com> wrote:

> Any thoughts on handling the case where a group A happens to have a single
> non-A taxon deeply nested within the group?
>
> (((((A1,B),A2),A3),A4),A5)mrca-A;
>
> In this case, we'd list the attachment points as A1, A2, A3, A4, A5, etc.
> The user might with to know which non-A taxa are present in the clade.
>
> There might be a number of queries to keep in mind:
>
>    - which non-A taxa are under this node?
>    - where are the A taxa under this node?
>    - which groups under this node contain no non-A taxa?
>    - of the N children of this node, perhaps only n contain taxa in A --
>    which ones?
>    - of the N chidlren of this node, perhaps only n contain taxa not in A
>    - which ones?
>
> Karen - thoughts? This seems to relate to our white-board discussion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenTreeOfLife/propinquity/issues/10#issuecomment-196477976>
> .
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~
karen.cranston@gmail.com
@kcranstn
~~~~~~~~~~~~~~~~~~~~~~~

**Comment by bredelings** [comment]
Well, A2 ... A5 are also tips, not internal nodes, if I've drawn the newick right.  So, they would get in too, right?  They don't contain B, at least...

**Comment by mtholder** [comment]
in response to @kcranston  and @bredelings : all of the internal nodes would be attachment points.

It is worth thinking about designing an alternative format that can be used in cases in which there are a small number of "intruders" causing a taxon to be non-monophyletic.

One correction to a previous comment I made: The sufficient set of source nodes to cause non-monophyly would be the set of source nodes in the `supported_by` or `partial_path_of` fields for all of the nodes that are in the tree induced by all of the attachment points (I previously said that the set of nodes would just be the leaves of that induced tree).

**Comment by bredelings** [comment]
Hmm... I think I get the attachment point concept now.  I guess in the case of "intruders" some of the attachment points can be ancestors of other attachment points.  

In the example above the most-tipward attachment point is also the attachment point of the lone "intruder" B, and the most-rootward attachment point is also the MRCA.

So, the list of minimal (most tipward) and maximal (most rootward) attachment points might be significant.

**Comment by mtholder** [comment]
closing because this info is now available in `labelled_supertree/broken_taxa.json` after `make html`
