### ISSUE TITLE
In a 'terminal' annotation, node should be identified using source tree node id, not OTT id

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/propinquity#11]
Spinning this off from https://github.com/OpenTreeOfLife/germinator/issues/50 , which is about something else. 

The annotations file has things like this:

```
        "ott716639": {
            "terminal": [
                [
                    "pg_2690_tree6243", 
                    "ott716639"
                ]
            ]
        }, 
```

Besides being redundant, the OTT id after "pg_2690_tree6243" doesn't make sense. To be consistent with the [documentation](https://github.com/OpenTreeOfLife/opentree/wiki/Conflict-and-synthesis-file-formats) and with the values provided by the other conflict/support relations, the terminal node ought to be a source tree node id, not an OTT id.

On the other issue @bredelings said "yeah, I think we should mention the node name w/in the study tree" which I believe means he agrees with this request.

This needs to be done before we release the v3 API.

**Comment by bredelings** [comment]
The nodeid of some OTUs is lost at some stage of the propinquity pipeline.  Given that this occurs before the subproblem solver, and only occurs for some of the tips, it could be that exemplified taxa are not getting their nodeid written out in otc-nonterminals-to-exemplars.  I hope to look at this next week.  

Does anything actually use the incorrect values yet?

**Comment by jar398** [comment]
Nothing uses the incorrect values, but we were talking about doing an API
and tree release on April 1, after which who knows what users might do. I'd
rather not show them OTT ids and then change it later, so it might be
better to suppress them. That date may slip, but it's still pretty urgent.

**Comment by mtholder** [comment]
It should not take long to hack in a step to:
  1. serialize a dict mapping ott id to node Id for each study in the cleaning and exemplifying steps,
  2. Fix the annotations file as a post processing step.

We can add something more elegant later.

**Comment by bredelings** [comment]
Hmm... I don't think the ottids without node names are going to actually be in the original study, since they are exemplifications.  So I'm not sure the hack would work.  But maybe I'm missing something...

Another approach would just be to modify replaceTipWithSet ( ) in _otc-nonterminals-to-exemplars_ to copy the node name from the replaced node.  There is a certain oddness about this, especially if a tip is expanded to multiple ottids.

**Comment by jar398** [comment]
"I don't think the ottids without node names are going to actually be in
the original study" - can you explain how that could possibly come about?
Where else would an OTT id come from, if not from an original study?

Exemplification is precisely the technique by which you can find a unique
node id for every OTT id associated with a tip in source tree. The OTT id
belongs to some OTUs, and the OTUs belong to some (tip) nodes, and one of
those nodes is the exemplar for that OTT id. So you can definitely map each
OTT id encountered in synthesis (before taxonomy 'reattachment') to a
unique node in a source tree, and that unique node has an id.  I presume
that if a node is taxonomy-only it won't have be `terminal`-related to
anything.

**Comment by mtholder** [comment]
If a tip node in a study to is mapped to the genus `Pan`, then the exemplification step in the supertree pipeline might turn this into 2 nodes that map to the 2 species within `Pan` (or whatever OTT has below `Pan`).

So the exemplified tree might have two nodes that map to a single node in the source tree. These cases of a higher taxon tip being replaced with a terminal taxon/taxa are the cases that show up as terminals in the annotations that lack node IDs.

It is not clear whether we want these annotated as terminal in the annotations.json. We could just suppress them.

In some sense the source tree touches these taxa, so one can imagine that some users interested in `Pan bonobo` might want to know all of the trees that say something about `Pan`. So in those cases, it would be nice for these users to see that there is a tip in a source tree that maps to a taxon that contains `Pan bonobo`.   
But these cases are a little odd, too. Because the source tree isn't saying anything about that terminal taxon specifically and because the source tree has a tip mapped to a containing taxon.

**Comment by jar398** [comment]
Suppressing the derived terminal annotations in this case would be OK.
Having a terminal annotation where the nodeid was that of the source node
that was mapped to the higher taxon (Pan) would also be OK.​

I think I will just add code to the plugin to look for "terminal"
properties with "ott..." values and delete them. Then you can decide what
to do about the problem at your leisure.

If a tree has 'Arthropoda' as a tip, then do all the 1 million+ Arthropoda
tips get roped in as honorary tips? Or only the Arthropoda tips that occur
in other source trees?

**Comment by mtholder** [comment]
Only Arthropoda used in other source trees. 
Or if none are used elsewhere, one terminal is chosen to be the exemplar.

**Comment by mtholder** [comment]
This stuff is confusing enough to document. We need to decide whether we want to:

  1. drop these exemplified taxa from the `terminal` info in the supporting info blob. In this case we'd want to add a caveat to the supporting info documentation that says something like "Note that if a leaf in a source study is mapped to higher taxon, that leaf will be expanded out to a set of exemplars during the supertree construction (as described in https://github.com/mtholder/propinquity/tree/master/exemplified_phylo). These exemplified terminals will not show up in the annotations."

or 

 2. include these terminals. Ben suggests (correctly) where we'd need to make this change in the otcetera code. It will not be a tough change to make.  If we do this, we should probably add something to the supporting information documentation like:  "Note that if a leaf in a source study is mapped to higher taxon, that leaf will be expanded out to a set of exemplars during the supertree construction (as described in https://github.com/mtholder/propinquity/tree/master/exemplified_phylo). Thus, when you look at a source tree node in the curation interface (or the raw phylesystem data) you may find that the OTT ID assigned to the node differs from the OTT ID found in the supertree annotations. This occurs because the interpretation of the source tree during the supertree algorithm associated the node with a descendant taxon."

**Comment by jar398** [comment]
Either is fine with me.

Another possibility is to introduce a new relation for this case, to
replace "terminal"? Like maybe [synth tree node] "exemplifies" [source tree
node]?

**Comment by mtholder** [comment]
fixed with https://github.com/mtholder/otcetera/commit/df5921fa2bca66edaf518cdcc38d319a004a4b90

tree posted to http://phylo.bio.ku.edu/ot/index.html
